#!/usr/bin/perl
#
# sms.pl - extracts UTF8 text from an input XML file
#
# Perl LibXML example:
# https://grantm.github.io/perl-libxml-by-example/basics.html
# source XML file generated by SMS Backup & Restore v10.20.002
# 2024-02-25

use 5.010;
use strict;
use warnings;

use XML::LibXML;
use open ':encoding(UTF-8)'; # input/output default encoding will be UTF-8

# --- begin ---

for my $arg (@ARGV)
  {
   if( -f $arg ) { xml_out( $arg ) }
   else { print 'Error: '. $arg .' - invalid input file .'."\n" }
  }

# --- end ---


sub xml_out
  {
   my ( $filename_in ) = @_ ;
   my ( $filename_out, $in, $dom, $out ) ;
   my ( $addr, $date_int, $date, $type, $body ) ;

   $filename_out = substr( $filename_in, 0, index( $filename_in,'.')) .'.txt' ;

   # open in file
   print 'Open file: '. $filename_in ."\n" ;
   open( $in,'<', $filename_in ) || die 'Error on open('. $filename_in .'): '. $! ."\n\n" ;
   binmode $in, ':raw';
   
   # open out file
   open( $out,'>'. $filename_out ) || die 'Error on open('. $filename_out .'): '. $! ."\n\n" ;
   
   $dom = XML::LibXML->load_xml(IO => $in) ;
   
   foreach my $sms ($dom->findnodes('//sms')) # XML node
     {
      $addr     = $sms->findvalue('./@address') ; # XML attribute
      $date_int = $sms->findvalue('./@date') ;
      $date     = $sms->findvalue('./@readable_date') ;
      $type     = $sms->findvalue('./@type') ;
      $body     = $sms->findvalue('./@body') ;
   
      print $out $type .'> '. $date_int .', '. $date .', '. $addr ."\n". $body ."\n" ;
     }
   
   print 'File '. $filename_out .' created.'."\n" ;
   close $out ;
   close $in ;
  }
